---
permalink: config-linux/fc-determine-host-port-wwpns-task.html 
sidebar: sidebar 
keywords: host wwpn, HBA utility, express linux configuration, software configuration, linux host, 
summary: 'Você instala um utilitário HBA FC para que você possa exibir o nome da porta mundial (WWPN) de cada porta host. Além disso, você pode usar o utilitário HBA para alterar as configurações recomendadas na coluna Notas da ferramenta de Matriz de interoperabilidade do NetApp para a configuração suportada.' 
---
= Determine WWPNs do host e faça as configurações recomendadas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você instala um utilitário HBA FC para que você possa exibir o nome da porta mundial (WWPN) de cada porta de host.

Além disso, pode utilizar o utilitário HBA para alterar as definições recomendadas na coluna Notas da https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] para a configuração suportada.

.Sobre esta tarefa
Reveja estas diretrizes para utilitários HBA:

* A maioria dos fornecedores de HBA oferece um utilitário HBA. Você precisará da versão correta do HBA para seu sistema operacional host e CPU. Exemplos de utilitários FC HBA incluem:
+
** Emulex OneCommand Manager para Emulex HBAs
** Console QLogic QConverge para HBAs QLogic




.Passos
. Baixe o utilitário apropriado do site do seu fornecedor HBA.
. Instale o utilitário.
. Selecione as definições apropriadas no utilitário HBA.
+
As configurações apropriadas para sua configuração são listadas na coluna Notas do https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^].


