---
permalink: config-linux/index.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Use a configuração expressa para um host Linux com um sistema e-Series. 
---
= Saiba mais sobre a configuração do Linux Express para e-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O método expresso Linux para instalar seu storage array e acessar o Gerenciador de sistemas do SANtricity é apropriado para configurar um host Linux autônomo em um sistema de storage e-Series. Ele foi projetado para colocar o sistema de storage em funcionamento o mais rápido possível com pontos de decisão mínimos.



== Descrição geral do procedimento

O método Linux Express inclui as seguintes etapas.

. Configure um dos seguintes ambientes de comunicação:
+
** Fibre Channel (FC)
** ISCSI
** SAS
** Iser em Infiniband
** SRP em Infiniband
** NVMe em Infiniband
** NVMe em RoCE
** NVMe em Fibre Channel


. Crie volumes lógicos no storage array.
. Disponibilize os volumes para o host de dados.




== Encontre mais informações

* Ajuda on-line -- descreve como usar o Gerenciador de sistemas do SANtricity para concluir as tarefas de gerenciamento de storage e configuração. Está disponível dentro do produto.
* https://kb.netapp.com/["Base de conhecimento da NetApp"^] (Um banco de dados de artigos) - fornece informações de solução de problemas, perguntas frequentes e instruções para uma ampla gama de produtos e tecnologias NetApp.
* http://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] -- permite pesquisar configurações de produtos e componentes NetApp que atendam aos padrões e requisitos especificados pela NetApp.

