---
permalink: config-linux/nvme-roce-create-filesystems-sles-15-task.html 
sidebar: sidebar 
keywords: file systems, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Para RHEL 9, RHEL 10, SLES 15 e SLES 16, você cria um sistema de arquivos no dispositivo nvme nativo e monta o sistema de arquivos. 
---
= Criar sistemas de arquivos na E-Series - Linux (NVMe sobre RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para RHEL 9, RHEL 10, SLES 15 e SLES 16, você cria um sistema de arquivos no dispositivo nvme nativo e monta o sistema de arquivos.

.Antes de começar
Certifique-se de ter concluído a link:nvme-roce-access-physical-targets-concept.html["acessando volumes NVMe para um E-Series target a partir do host"] tarefa para garantir que os dispositivos NVMe estejam configurados corretamente e acessíveis.

.Passos
. Crie um sistema de arquivos na partição para o dispositivo nvme desejado usando o local `/dev/disk/by-id/nvme-eui.[id#]`.
+
O método para criar um sistema de arquivos varia dependendo do sistema de arquivos escolhido. Este exemplo mostra a criação de um `ext4` sistema de arquivos.

+
[listing]
----
# mkfs.ext4 /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225
mke2fs 1.42.11 (22-Oct-2019)
Creating filesystem with 2620928 4k blocks and 655360 inodes
Filesystem UUID: 97f987e9-47b8-47f7-b434-bf3ebbe826d0
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done
----
. Crie uma pasta para montar o novo dispositivo.
+
[listing]
----
# mkdir /mnt/ext4
----
. Monte o dispositivo.
+
[listing]
----
# mount /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225 /mnt/ext4
----


.O que se segue?
Após criar os sistemas de arquivos, link:nvme-roce-worksheet-for-concept.html["Registre suas informações de configuração do NVMr sobre RoCE"].
