---
permalink: config-linux/nvme-roce-create-filesystems-sles-15-task.html 
sidebar: sidebar 
keywords: file systems, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Para o SLES 15, você cria um sistema de arquivos no dispositivo nvme nativo e monta o sistema de arquivos. 
---
= Criar sistemas de arquivos (RHEL 8, RHEL 9 e SLES 15)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para RHEL 8, RHEL 9 e SLES 15, você cria um sistema de arquivos no dispositivo nvme nativo e monta o sistema de arquivos.

.Passos
. Execute o `multipath -ll` comando para obter uma lista de dispositivos nvme.
+
[listing]
----
# multipath -ll
----
+
O resultado deste comando pode ser usado para localizar a localização associada aos dispositivos `/dev/disk/by-id/nvme-eui.[uuid#]`. Para o exemplo abaixo, isso `/dev/disc/by-id/nvme-eui.000082dd5c05d39300a0980000a52225` seria .

+
[listing]
----
eui.000082dd5c05d39300a0980000a52225 [nvme]:nvme0n6 NVMe,NetApp E-Series,08520000
size=4194304 features='n/a' hwhandler='ANA' wp=rw
|-+- policy='n/a' prio=50 status=optimized
| `- 0:0:1 nvme0c0n1 0:0 n/a optimized     live
|-+- policy='n/a' prio=50 status=optimized
| `- 0:1:1 nvme0c1n1 0:0 n/a optimized     live
|-+- policy='n/a' prio=10 status=non-optimized
| `- 0:2:1 nvme0c2n1 0:0 n/a non-optimized live
`-+- policy='n/a' prio=10 status=non-optimized
  `- 0:3:1 nvme0c3n1 0:0 n/a non-optimized live
----
. Crie um sistema de arquivos na partição para o dispositivo nvme desejado usando o local `/dev/disk/by-id/nvme-eui.[id#]`.
+
O método para criar um sistema de arquivos varia dependendo do sistema de arquivos escolhido. Este exemplo mostra a criação de um `ext4` sistema de arquivos.

+
[listing]
----
# mkfs.ext4 /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225
mke2fs 1.42.11 (22-Oct-2019)
Creating filesystem with 2620928 4k blocks and 655360 inodes
Filesystem UUID: 97f987e9-47b8-47f7-b434-bf3ebbe826d0
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done
----
. Crie uma pasta para montar o novo dispositivo.
+
[listing]
----
# mkdir /mnt/ext4
----
. Monte o dispositivo.
+
[listing]
----
# mount /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225 /mnt/ext4
----

