---
permalink: config-linux/nvme-roce-verify-linux-config-support-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Para garantir uma operação confiável, você cria um plano de implementação e, em seguida, usa a ferramenta de Matriz de interoperabilidade (IMT) do NetApp para verificar se toda a configuração é suportada.' 
---
= Verificar o suporte à configuração do Linux e revisar as restrições no e-Series (NVMe sobre RoCE)
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como primeira etapa, você deve verificar se sua configuração do Linux é suportada e também revisar as restrições de controladora, switch, host e recuperação.



[[verify-the-linux-configuration-is-supported]]
== Verifique se a configuração do Linux é suportada

Para garantir uma operação confiável, você cria um plano de implementação e, em seguida, usa a ferramenta de Matriz de interoperabilidade (IMT) do NetApp para verificar se toda a configuração é suportada.

.Passos
. Vá para https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] .
. Clique no bloco *Pesquisa de solução*.
. Na área menu:Protocolos[Host SAN], clique no botão *Add* ao lado de *e-Series SAN Host*.
. Clique em *Exibir critérios de pesquisa de refino*.
+
É apresentada a secção refinar critérios de pesquisa. Nesta seção, você pode selecionar o protocolo que se aplica, bem como outros critérios para a configuração, como sistema operacional, NetApp os e driver de vários caminhos de host.

. Selecione os critérios que você sabe que deseja para sua configuração e veja quais elementos de configuração compatíveis se aplicam.
. Conforme necessário, faça as atualizações para o seu sistema operativo e protocolo que são prescritas na ferramenta.
+
As informações detalhadas para a configuração escolhida estão acessíveis na página Exibir configurações suportadas clicando na seta da página direita.





[[verify-nvme-over-roce-restrictions]]
== Verifique as restrições do NVMe sobre RoCE

Antes de usar o NVMe em RoCE, consulte o https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] para verificar as restrições mais recentes de controladora, host e recuperação.



[[switch-restrictions]]
=== Restrições do interrutor


CAUTION: *RISCO DE PERDA DE DADOS.* Você deve executar NVMe sobre RoCE em um ambiente sem perdas. Habilite controle de fluxo de ponta a ponta usando Quadros de Pausa Global ou Controle de Fluxo Prioritário (PFC) em sua rede para eliminar o risco de perda de dados. O PFC exige que o tráfego NVMe sobre RoCE seja marcado como tráfego de Prioridade 3 com um valor DSCP de `106`.



[[storage-and-disaster-recovery-restrictions]]
=== Restrições de armazenamento e recuperação de desastres

* Espelhamento assíncrono e síncrono não são compatíveis.
* O thin Provisioning (a criação de thin volumes) não é suportado.


.O que se segue?
Após verificar a compatibilidade com a configuração do Linux e revisar as restrições, link:nvme-roce-configure-ip-address-dhcp-task.html["configurar endereços IP usando DHCP"].
