---
permalink: config-linux/nvme-roce-discover-connect-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage, host, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Antes de definir cada host no Gerenciador de sistemas do SANtricity, você precisa descobrir as portas do controlador de destino do host e, em seguida, estabelecer conexões NVMe. 
---
= Descubra e conecte-se ao storage a partir do host no e-Series - Linux (NVMe em RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de definir cada host no Gerenciador de sistemas do SANtricity, você precisa descobrir as portas do controlador de destino do host e, em seguida, estabelecer conexões NVMe.

.Passos
. Verifique se você consegue pingar do host para cada porta HIC do array usando a taxa MTU esperada com o seguinte comando:
+
[listing]
----
ping -M do -s <size> <IP of array HIC port>
----
. Descubra os subsistemas disponíveis no destino NVMe-of para todos os caminhos usando o seguinte comando:
+
[listing]
----
nvme discover -t rdma -a target_ip_address
----
+
Neste comando `target_ip_address`, é o endereço IP da porta de destino.

+

NOTE: O `nvme discover` comando descobre todas as portas do controlador no subsistema, independentemente do acesso do host.

+
[listing]
----
# nvme discover -t rdma -a 192.168.1.77
Discovery Log Number of Records 2, Generation counter 0
=====Discovery Log Entry 0======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  0
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94
traddr:  192.168.1.77
rdma_prtype: roce
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
=====Discovery Log Entry 1======
trtype:  rdma
adrfam:  ipv4
subtype: nvme subsystem
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:5700.600a098000a527a7000000005ab3af94
traddr:  192.168.2.77
rdma_prtype: roce
rdma_qptype: connected
rdma_cms:    rdma-cm
rdma_pkey: 0x0000
----
. Repita o passo 2 para quaisquer outras conexões.
. Conete-se ao subsistema descoberto no primeiro caminho usando o comando: `nvme connect -t rdma -n discovered_sub_nqn -a target_ip_address -Q queue_depth_setting -l controller_loss_timeout_period`
+

NOTE: O comando listado acima não persiste após reinicializar. O `nvme connect` comando precisará ser executado após cada reinicialização para restabelecer as conexões NVMe.

+

NOTE: As conexões não são estabelecidas para qualquer porta descoberta inacessível pelo host.

+

NOTE: Se você especificar um número de porta usando este comando, a conexão falhará. A porta padrão é a única porta configurada para conexões.

+

NOTE: A profundidade de fila recomendada é 1024. Substitua a configuração padrão de 128 por 1024 usando a opção de linha de comando `-Q 1024`, conforme mostrado no exemplo a seguir.

+

NOTE: O período de tempo limite de perda recomendado do controlador em segundos é de 60 minutos (3600 segundos). Substitua a configuração padrão de 600 segundos com 3600 segundos usando a `-l 3600` opção de linha de comando, como mostrado no exemplo a seguir.

+
[listing]
----
# nvme connect -t rdma -a 192.168.1.77 -n nqn.1992-
08.com.netapp:EF80.600a098000a527a7000000005ab3af94 -Q 1024 -l 3600
----
. Repita o passo 4 para conectar o subsistema descoberto no segundo caminho.
. **Opcional** - Configure seu host para descobrir e se conectar automaticamente aos alvos a cada inicialização.
+
.. Adicione os parâmetros de descoberta das etapas 2 e 3 a `/etc/nvme/discovery.conf` usando o seguinte procedimento e formato:
+
[listing]
----
# echo "--transport=rdma --traddr= target_ip_address --trsvcid=4420" | sudo tee -a /etc/nvme/discovery.conf
----
.. Habilite o serviço nvmf-autoconnect após preencher o arquivo  `/etc/nvme/discovery.conf` usando o seguinte comando:
+
[listing]
----
sudo systemctl enable nvmf-autoconnect.service
----




.O que se segue?
Após estabelecer as conexões, link:nvme-roce-define-host-task.html["definir o host"].
