---
permalink: config-linux/nvme-ib-set-up-failover-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Configure o host para executar o failover. 
---
= Configurar failover no host em e-Series - Linux (NVMe over InfiniBand)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para fornecer um caminho redundante para o storage array, você pode configurar o host para executar o failover.

.Antes de começar
Você deve instalar os pacotes necessários em seu sistema.

* Para hosts Red Hat (RHEL), verifique se os pacotes estão instalados executando `rpm -q device-mapper-multipath`
* Para hosts SLES, verifique se os pacotes estão instalados executando `rpm -q multipath-tools`
+

NOTE:  https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^]Consulte para garantir que todas as atualizações necessárias sejam instaladas, pois o multipathing pode não funcionar corretamente com as versões GA do SLES ou RHEL.



 SLES 12 use Device Mapper Multipath (DMMP) for multipathing when using NVMe over Infiniband. RHEL 8, RHEL 9, RHEL 10, SLES 15 and SLES 16 use a built-in Native NVMe Failover. Depending on which OS you are running, some additional configuration of multipath is required to get it running properly.


== Ativar o Device Mapper Multipath (DMMP) SLES 12

Por padrão, o DM-MP está desabilitado no SLES. Conclua as etapas a seguir para ativar os componentes DM-MP no host.

.Passos
. Adicione a entrada do dispositivo NVMe e-Series à seção dispositivos do arquivo /etc/multipath.conf, como mostrado no exemplo a seguir:
+
[listing]
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----
. Configure `multipathd` para iniciar na inicialização do sistema.
+
[listing]
----
# systemctl enable multipathd
----
. Inicie `multipathd` se não estiver em execução no momento.
+
[listing]
----
# systemctl start multipathd
----
. Verifique o estado de `multipathd` para se certificar de que está ativo e em execução:
+
[listing]
----
# systemctl status multipathd
----




== Configurando o RHEL 8 com o Native NVMe Multipathing

O NVMe Multipathing nativo é desativado por padrão no RHEL 8 e deve ser habilitado usando as etapas abaixo.

. Regra de `modprobe` configuração para ativar o NVMe Multipathing nativo.
+
[listing]
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----
. Remake `initramfs` com novo `modprobe` parâmetro.
+
[listing]
----
# dracut -f
----
. Reinicie o servidor para ativá-lo com o Native NVMe Multipathing habilitado.
+
[listing]
----
# reboot
----
. Verifique se a opção de multipathing NVMe nativo foi ativada depois que o host inicializa o backup.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
.. Se o comando output for `N`, então o Native NVMe Multipathing ainda será desativado.
.. Se o comando output for `Y`, então o Native NVMe Multipathing será ativado e todos os dispositivos NVMe que você descobrir o usarão.





NOTE: Para SLES 15, SLES 16, RHEL 9 e RHEL 10, o Native NVMe Multipathing está habilitado por padrão e nenhuma configuração adicional é necessária.
