---
permalink: config-linux/nvme-roce-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Configure o host para executar o failover. 
---
= Configurar failover no host no e-Series - Linux (NVMe sobre RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para fornecer um caminho redundante para o storage array, você pode configurar o host para executar o failover.

.Antes de começar
Consulte o  https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] para garantir que todas as atualizações necessárias estejam instaladas, pois correções de bugs importantes podem ser necessárias para versões do SLES ou RHEL que não estão disponíveis na versão inicial.

.Sobre esta tarefa
Para SLES 15, SLES 16, RHEL 9 e RHEL 10, o Native NVMe Multipathing está habilitado por padrão e nenhuma configuração adicional é necessária.

.O que se segue?
Com o Multipathing NVMe nativo ativado, link:nvme-roce-access-physical-targets-concept.html["Acesse os volumes NVMe de um E-Series alvo a partir do host"].
