---
permalink: config-linux/overview-concept.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Revise os requisitos para usar o método Express para configurar um array e-Series e um host Linux. 
---
= Suposições (e-Series e Linux)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O método Linux Express é baseado nas seguintes suposições:

|===
| Componente | Suposições 


 a| 
Hardware
 a| 
* Você usou as instruções de instalação e configuração incluídas nas prateleiras da controladora para instalar o hardware.
* Você conectou cabos entre as gavetas de unidade opcionais e as controladoras.
* Você aplicou energia ao sistema de armazenamento.
* Você instalou todo o outro hardware (por exemplo, estação de gerenciamento, switches) e fez as conexões necessárias.
* Se você estiver usando NVMe em Infiniband, NVMe em RoCE ou NVMe em Fibre Channel, cada controladora EF300, EF600, EF570 ou E5700 terá pelo menos 32 GB de RAM.




 a| 
Host
 a| 
* Você fez uma conexão entre o sistema de armazenamento e o host de dados.
* Você instalou o sistema operacional host.
* Você não está usando o Linux como um convidado virtualizado.
* Você não está configurando o host de dados (e/S anexado) para inicializar a partir da SAN.
* Você instalou todas as atualizações do sistema operacional conforme listado em https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] .




 a| 
Estação de gerenciamento de armazenamento
 a| 
* Você está usando uma rede de gerenciamento de 1 Gbps ou mais rápida.
* Você está usando uma estação separada para gerenciamento, em vez do host de dados (e/S anexado).
* Você está usando o gerenciamento fora da banda, no qual uma estação de gerenciamento de storage envia comandos ao sistema de storage por meio das conexões Ethernet ao controlador.
* Você conetou a estação de gerenciamento à mesma sub-rede que as portas de gerenciamento de armazenamento.




 a| 
Endereçamento IP
 a| 
* Instalou e configurou um servidor DHCP.
* * Ainda não* fez uma conexão Ethernet entre a estação de gerenciamento e o sistema de armazenamento.




 a| 
Provisionamento de storage
 a| 
* Você não usará volumes compartilhados.
* Você criará pools em vez de grupos de volume.




 a| 
Protocolo: FC
 a| 
* Você fez todas as conexões FC do lado do host e ativou o zoneamento do switch.
* Você está usando HBAs e switches FC compatíveis com NetApp.
* Você está usando versões de driver e firmware FC HBA, conforme listado no https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^].




 a| 
Protocolo: ISCSI
 a| 
* Você está usando switches Ethernet capazes de transportar tráfego iSCSI.
* Você configurou os switches Ethernet de acordo com a recomendação do fornecedor para iSCSI.




 a| 
Protocolo: SAS
 a| 
* Você está usando HBAs SAS compatíveis com NetApp.
* Você está usando as versões de driver e firmware HBA SAS, conforme listado no https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^].




 a| 
Protocolo: Emissor em InfiniBand
 a| 
* Você está usando um InfiniBand Fabric.
* Você está usando versões de driver e firmware do IB-iSER HBA, conforme listado no https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^].




 a| 
Protocolo: SRP em InfiniBand
 a| 
* Você está usando um InfiniBand Fabric.
* Você está usando versões de driver e firmware IB-SRP conforme listado no https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^].




 a| 
Protocolo: NVMe em InfiniBand
 a| 
* Você recebeu as placas de interface de host 100g ou 200g em um sistema de storage EF300, EF600, EF570 ou E5700 pré-configurado com o protocolo NVMe over InfiniBand ou as controladoras foram solicitadas com portas IB padrão e precisam ser convertidas em portas NVMe-of.
* Você está usando um InfiniBand Fabric.
* Você está usando versões de driver e firmware NVMe/IB, conforme listado no https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^].




 a| 
Protocolo: NVMe em RoCE
 a| 
* Você recebeu as placas de interface de host 100g ou 200g em um sistema de storage EF300, EF600, EF570 ou E5700 pré-configurado com o protocolo NVMe sobre RoCE ou as controladoras foram solicitadas com portas IB padrão e precisam ser convertidas em portas NVMe-of.
* Você está usando versões de driver e firmware NVMe/RoCE, conforme listado no https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^].




 a| 
Protocolo: NVMe em Fibre Channel
 a| 
* Você recebeu as 32G placas de interface de host em um sistema de storage EF300, EF600, EF570 ou E5700 pré-configurado com o protocolo NVMe sobre Fibre Channel ou as controladoras foram solicitadas com portas FC padrão e precisam ser convertidas em portas NVMe-of.
* Você está usando versões de driver e firmware NVMe/FC conforme listado no https://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^].


|===

NOTE: Estas instruções de método expresso incluem exemplos para SUSE Linux Enterprise Server (SLES) e para Red Hat Enterprise Linux (RHEL).
