---
permalink: maintenance-e2800/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: E2800 replace HIC, E2800 replace host interface card, replacing E2800 HIC, E2800 replace HIC, adding E2800 HIC, upgrading E2800 HIC, E2800, E-Series, eseries 
summary: Rever os requisitos para a substituição HIC E2800. 
---
= Requisitos para a substituição de E2800 HIC
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de adicionar, atualizar ou substituir uma placa de interface de host (HIC) em um E2800, revise os requisitos e considerações.



== Descrição geral do procedimento

As etapas para substituir um HIC dependem se você tem um ou dois controladores, como segue:

|===
| Se a sua matriz de armazenamento tem... | Você deve... 


 a| 
Um controlador (E2812 ou E2824 simplex)
 a| 
. Parar as operações de e/S do host
. Desligue o compartimento do controlador
. Retire o recipiente do controlador
. Substitua a bateria
. Substitua o recipiente do controlador
. Aplique energia na gaveta do controlador




 a| 
Dois controladores (E2860, E2812 ou E2824 duplex)
 a| 
. Coloque o controlador offline
. Retire o recipiente do controlador
. Substitua a bateria
. Substitua o recipiente do controlador
. Coloque o controlador online


|===


== Requisitos para adicionar, atualizar ou substituir um HIC

Se você planeja adicionar, atualizar ou substituir uma placa de interface de host (HIC), tenha em mente os seguintes requisitos.

* Você agendou uma janela de manutenção de tempo de inatividade para este procedimento. A energia deve estar desligada quando você instala HICs, para que você não possa acessar dados no storage de armazenamento até que você tenha concluído com êxito este procedimento. (Em uma configuração duplex, isso ocorre porque ambos os controladores devem ter a mesma configuração HIC quando são ligados.)
* Você tem uma ou duas HICs, com base se você tem um ou dois controladores em seu storage array. As placas de rede de interligação local (HICs) têm de ser compatíveis com os controladores.
+
Se você tiver uma configuração duplex (dois controladores), as HICs instaladas nos dois coletores de controladora devem ser idênticas. A presença de HICs incompatíveis faz com que o controlador com o HIC de substituição bloqueie quando o coloca online.

* Você tem todos os cabos, transcetores, switches e adaptadores de barramento do host (HBAs) necessários para conetar as novas portas do host.
+
Para obter informações sobre o hardware compatível, consulte a https://mysupport.netapp.com/NOW/products/interoperability["Matriz de interoperabilidade do NetApp"^] ou a http://hwu.netapp.com/home.aspx["NetApp Hardware Universe"^].

* Você tem uma pulseira antiestática ou tomou outras precauções antiestáticas.
* Você tem uma chave de fenda Phillips nº 1.
* Você tem etiquetas para identificar cada cabo que está conetado ao recipiente do controlador.
* Você tem uma estação de gerenciamento com um navegador que pode acessar o Gerenciador de sistema do SANtricity para o controlador. (Para abrir a interface do System Manager, aponte o navegador para o nome de domínio ou endereço IP do controlador.)

