---
sidebar: sidebar 
permalink: manage-storage.html 
keywords: online help, System Manager, Unified Manager 
summary: Gerenciar o storage 
---
= Gerenciar o storage
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Use os links abaixo para acessar a documentação que descreve como configurar, gerenciar e monitorar objetos de storage e sistemas de storage e-Series. Os links levam você a um site de documentação diferente.



== Ajuda online para System Manager

Acesse o https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html["Ajuda online do Gestor de sistema SANtricity"^], onde você pode encontrar informações sobre como Planejar, configurar, gerenciar e solucionar problemas do storage array.



== Ajuda on-line do Unified Manager

Acesse o https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html["Ajuda online do SANtricity Unified Manager"^], onde você pode aprender a executar comandos de gerenciamento de armazenamento em vários storages de armazenamento de rede.



== Referência do comando

Acesse o https://docs.netapp.com/us-en/e-series-cli/index.html["Referência do comando"^], onde você pode aprender a configurar e monitorar seus storage arrays usando comandos de interface de linha de comando (CLI).
