---
sidebar: sidebar 
permalink: rackmount-hardware.html 
keywords: rackmount, rack-mount, install in rack, rails 
summary: O hardware para montagem em rack é usado para instalar seu hardware em um rack ou gabinete. As instruções de instalação devem estar incluídas na caixa do hardware para montagem em rack. No entanto, se precisar acessar as instruções de instalação, use o link correspondente abaixo. 
---
= Hardware para montagem em rack - E-Series
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O hardware de montagem em rack é usado para instalar seu sistema de storage em um rack ou gabinete. As instruções de instalação devem estar incluídas na caixa do hardware de montagem em rack. No entanto, se precisar acessar as instruções de instalação, use o link correspondente abaixo.

Para sistemas de armazenamento mais recentes, você pode verificar o hardware de montagem em rack compatível consultando o NetApp Hardware Universe em https://hwu.netapp.com["NetApp Hardware Universe"^].



== Calhas de suporte ajustáveis

Acesso https://mysupport.netapp.com/ecm/ecm_download_file/ECMP1652045["Instalação de calhas de suporte ajustáveis"^] para instalar uma bandeja de unidades e controlador ou uma bandeja de unidades fornecida separadamente (ainda não instalada no gabinete). Este procedimento é aplicável às seguintes bandejas de 2U (9 cm ou 3,5 polegadas):

* DE1600 ou DE5600
* E2612 ou E2624
* E5412, E5424, E5512 OU E5524




== Rack de dois pilares -- 2U

 https://mysupport.netapp.com/ecm/ecm_download_file/ECMM1280302["Instalação de equipamentos 2U em um rack de dois pilares"^]Acesso .



== Rack de quatro colunas ou gabinete -- 2U

 https://mysupport.netapp.com/ecm/ecm_download_file/ECMLP2484194["Instalação de um gabinete de 2U 12 unidades em um rack ou gabinete de quatro colunas"^]Acesso .



== Rack de quatro colunas -- SuperRail

Acessar https://docs.netapp.com/us-en/ontap-systems/platform-supplemental/superrail-install.html["Instale SuperRail em um rack de quatro postes"^].
