---
permalink: config-vmware/configure-multipath-software-concept.html 
sidebar: sidebar 
keywords: multipath software for vmware, express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Configure o software m para fornecer um caminho redundante para o storage array no caso de um dos caminhos físicos ser interrompido. 
---
= Configurar o software multipath
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para fornecer um caminho redundante para o storage array, você pode configurar o software multipath.

O software multipath fornece um caminho redundante para o storage array no caso de um dos caminhos físicos ser interrompido. O software multipath apresenta ao sistema operacional um único dispositivo virtual que representa os caminhos físicos ativos para o storage. O software multipath também gerencia o processo de failover que atualiza o dispositivo virtual. Para VMware, o NVMe/FC usa o High Performance Plugin (HPP).

Aplicável apenas aos protocolos FC, iSCSI e SAS, a VMware fornece plug-ins, conhecidos como Storage Array Type Plug-ins (SATP), para lidar com implementações de failover de arrays de storage de fornecedores específicos.

O SATP que você deve usar é *VMW_SATP_ALUA*.

Para obter mais informações, https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-DB5BC795-E4D9-4350-9C5D-12BB3C0E6D99.html["SATPs da VMware"^]consulte .
