---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-storage-array-passwords.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Atualize as senhas usadas para visualizar e acessar matrizes de armazenamento no plug-in de armazenamento para vCenter. 
---
= Alterar senhas de storage array no plug-in de armazenamento SANtricity para vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode atualizar as senhas usadas para visualizar e acessar matrizes de armazenamento no plug-in de armazenamento para vCenter.

.Antes de começar
Você deve saber a senha atual para a matriz de armazenamento, que é definida no System Manager.

.Sobre esta tarefa
Nesta tarefa, você insere a senha atual de um storage array para que você possa acessá-lo no plugin. Isso pode ser necessário se a senha do array tiver sido alterada no System Manager.

.Passos
. Na página *Gerenciar*, selecione um ou mais storages.
. Selecione menu:tarefas incomuns[fornecer senhas de storage array].
. Insira a senha ou as senhas de cada matriz de armazenamento e clique em *Salvar*.

