---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-autosupport-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Importe uma configuração do AutoSupport de um storage array para outros storage arrays. 
---
= Importar definições do AutoSupport
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode importar uma configuração do AutoSupport de um storage array para outros storage arrays. Esta operação em lote economiza tempo quando você precisa configurar vários arrays na rede.

.Antes de começar
Certifique-se de que:

* O AutoSupport está configurado no Gerenciador de sistema (menu:suporte[Centro de suporte]) para a matriz de armazenamento que você deseja usar como origem.
* A configuração existente para os storages de armazenamento de destino é feita com backup no System Manager (menu:Configurações[sistema > Salvar configuração da matriz de armazenamento]).
* Você analisou os requisitos para replicação de configurações de storage no link:vc-olh-import-settings-overview.html["Descrição geral das definições de importação"].


.Sobre esta tarefa
As configurações importadas incluem os recursos separados (Basic AutoSupport, AutoSupport OnDemand e Remote Diagnostics), a janela de manutenção, o método de entrega e o agendamento de envio.

.Passos
. Na página Gerenciar, clique em menu:ações[Importar configurações].
+
O assistente Importar configurações é aberto.

. Na caixa de diálogo Selecionar configurações, selecione *AutoSupport* e clique em *Avançar*.
+
Abre-se uma caixa de diálogo para selecionar a matriz de origem.

. Na caixa de diálogo Selecionar fonte, selecione a matriz com as configurações que deseja importar e clique em *Avançar*.
. Na caixa de diálogo Selecionar destinos, selecione um ou mais arrays para receber as novas configurações.
+

NOTE: Matrizes de armazenamento com firmware abaixo de 8,50 não estão disponíveis para seleção. Além disso, uma matriz não aparece nesta caixa de diálogo se o plugin não puder se comunicar com essa matriz (por exemplo, se estiver offline ou se tiver problemas de certificado, senha ou rede).

. Clique em *Finish*.
+
A página operações exibe os resultados da operação de importação. Se a operação falhar, você pode clicar em sua linha para ver mais informações.



.Resultado
Os storages de armazenamento de destino agora são configurados com as mesmas configurações de AutoSupport que o array de origem.
