---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-remove-storage-arrays.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Remova um ou mais arrays de armazenamento se você não quiser mais gerenciá-lo a partir do plug-in de armazenamento para vCenter. 
---
= Remova os storage arrays no plug-in de armazenamento do SANtricity para vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode remover um ou mais arrays de armazenamento se não quiser mais gerenciá-lo do plug-in de armazenamento para vCenter.

.Sobre esta tarefa
Não é possível acessar nenhum dos storages de armazenamento que você remover. Você pode, no entanto, estabelecer uma conexão com qualquer um dos storages removidos apontando um navegador diretamente para seu endereço IP ou nome de host.

A remoção de um storage array não afeta o storage array ou seus dados de forma alguma. Se uma matriz de armazenamento for removida acidentalmente, ela pode ser adicionada novamente.

.Passos
. Na página *Gerenciar*, selecione um ou mais arrays de armazenamento que você deseja remover.
. Selecione menu:tarefas incomuns[Remover matrizes de armazenamento].
+
O storage array é removido de todas as visualizações na interface do plugin.


