---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-clear-staged-os-software.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Você pode remover o software de sistema operacional em estágios para garantir que uma versão pendente não seja ativada inadvertidamente posteriormente. 
---
= Limpar o software do sistema operacional em estágios no plug-in de armazenamento do SANtricity para vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode remover o software de sistema operacional em estágios para garantir que uma versão pendente não seja ativada inadvertidamente posteriormente. A remoção do software do SO em estágio não afeta a versão atual que está sendo executada nos storages de armazenamento.

.Passos
. Na exibição principal, selecione *Gerenciar* e, em seguida, selecione menu:Centro de Atualização[Limpar software SANtricity encenado].
+
A caixa de diálogo Clear Staged SANtricity Software (Limpar software em estágios) abre e lista todos os sistemas de armazenamento descobertos com software pendente ou NVSRAM.

. Se necessário, filtre ou classifique os sistemas de storage na lista para que você possa visualizar todos os sistemas que tenham feito o software em estágios.
. Marque as caixas de seleção dos sistemas de armazenamento com software pendente que você deseja desmarcar.
. Clique em *Limpar*.
+
O estado da operação é apresentado na caixa de diálogo.


