---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-is-optimization-capacity-for-pools.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: As unidades SSD terão vida útil mais longa e melhor desempenho máximo de gravação quando uma parte de sua capacidade não for alocada. 
---
= O que é a capacidade de otimização para pools?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
As unidades SSD terão vida útil mais longa e melhor desempenho máximo de gravação quando uma parte de sua capacidade não for alocada.

Para unidades associadas a um pool, a capacidade não alocada é composta pela capacidade de preservação de um pool, pela capacidade livre (capacidade não usada por volumes) e por uma parte da capacidade utilizável reservada como capacidade de otimização adicional. A capacidade de otimização adicional garante um nível mínimo de capacidade de otimização, reduzindo a capacidade utilizável, e, como tal, não está disponível para criação de volume.

Quando um pool é criado, uma capacidade de otimização recomendada é gerada, que fornece um equilíbrio de desempenho, vida útil do desgaste e capacidade disponível. O controle deslizante capacidade de otimização adicional localizado na caixa de diálogo Configurações do pool permite ajustes na capacidade de otimização do pool. O ajuste da barra deslizante proporciona um melhor desempenho e vida útil do desgaste à custa da capacidade disponível, ou da capacidade disponível adicional à custa do desempenho e da vida útil do desgaste da transmissão.


NOTE: O controle deslizante capacidade de otimização adicional está disponível apenas para sistemas de armazenamento EF600 e EF300.
