---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-assign-volumes-to-hosts.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: É necessário atribuir um volume a um host ou a um cluster de host para que ele possa ser usado para operações de e/S. 
---
= Atribuir volumes aos hosts
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
É necessário atribuir um volume a um host ou a um cluster de host para que ele possa ser usado para operações de e/S.

.Antes de começar
Tenha estas diretrizes em mente quando atribuir volumes a hosts:

* Você pode atribuir um volume a apenas um host ou cluster de host de cada vez.
* Os volumes atribuídos são compartilhados entre controladores no storage array.
* O mesmo número de unidade lógica (LUN) não pode ser usado duas vezes por um host ou um cluster de host para acessar um volume. Você deve usar um LUN exclusivo.
* Para novos grupos de volumes, se você esperar até que todos os volumes sejam criados e inicializados antes de atribuí-los a um host, o tempo de inicialização do volume será reduzido. Tenha em mente que, uma vez que um volume associado ao grupo de volumes é mapeado, todos os volumes reverterão para a inicialização mais lenta.


.Sobre esta tarefa
Uma atribuição de volume concede a um host ou cluster de host acesso a esse volume em um storage array.

Todos os volumes não atribuídos são exibidos durante esta tarefa, mas as funções para hosts com ou sem Garantia de dados (DA) se aplicam da seguinte forma:

* Para um host compatível com DA, você pode selecionar volumes habilitados PARA DA ou não habilitados PARA DA.
* Para um host que não é capaz de DA, se você selecionar um volume que é habilitado PARA DA, um aviso indica que o sistema deve DESLIGAR automaticamente DA no volume antes de atribuir o volume ao host.
+
A atribuição de um volume falha nestas condições:

* Todos os volumes são atribuídos.
* O volume já está atribuído a outro host ou cluster de host. A capacidade de atribuir um volume não está disponível nestas condições:
* Não existem hosts ou clusters de host válidos.
* Nenhum identificador de porta de host foi definido para o host.
* Todas as atribuições de volume foram definidas.


.Passos
. Na página Gerenciar, selecione a matriz de armazenamento com a conexão do host.
. Selecione menu:provisionamento[Configurar hosts].
+
A página Configurar hosts será exibida.

. Selecione o host ou cluster de host ao qual você deseja atribuir volumes e clique em *atribuir volumes*.
+
É apresentada uma caixa de diálogo que lista todos os volumes que podem ser atribuídos. Você pode classificar qualquer uma das colunas ou digitar algo na caixa filtro para facilitar a localização de volumes específicos.

. Marque a caixa de seleção ao lado de cada volume que você deseja atribuir ou marque a caixa de seleção no cabeçalho da tabela para selecionar todos os volumes.
. Clique em *Assign* para concluir a operação.


.Resultados
Depois de atribuir com êxito um volume ou volumes a um host ou a um cluster de host, o sistema executa as seguintes ações:

* O volume atribuído recebe o próximo número de LUN disponível. O host usa o número LUN para acessar o volume.
* O nome do volume fornecido pelo usuário aparece nas listagens de volume associadas ao host. Se aplicável, o volume de acesso configurado de fábrica também aparece nas listagens de volume associadas ao host.

