---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-why-are-some-drives-not-showing-up.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Na caixa de diálogo Adicionar capacidade, nem todas as unidades estão disponíveis para adicionar capacidade a um pool ou grupo de volumes existente. 
---
= Por que algumas unidades não estão aparecendo?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Na caixa de diálogo Adicionar capacidade, nem todas as unidades estão disponíveis para adicionar capacidade a um pool ou grupo de volumes existente.

As unidades não são qualificadas por nenhum dos seguintes motivos:

* Uma unidade deve ser desatribuída e não ativada para segurança. As unidades que já fazem parte de outro pool, de outro grupo de volume ou configuradas como hot spare não são elegíveis. Se uma unidade não for atribuída, mas estiver ativada para segurança, você deverá apagar manualmente essa unidade para que ela se torne elegível.
* Uma unidade que esteja em um estado não ótimo não é elegível.
* Se a capacidade de uma unidade for muito pequena, ela não será elegível.
* O tipo de Mídia da unidade deve corresponder em um pool ou grupo de volume. Não é possível misturar o seguinte:
+
** Unidades de disco rígido (HDDs) com discos de estado sólido (SSDs)
** NVMe com unidades SAS
** Unidades com tamanhos de bloco de volume de 512 bytes e 4KiB


* Se um pool ou grupo de volumes contiver todas as unidades com capacidade de segurança, as unidades com capacidade de segurança não serão listadas.
* Se um pool ou grupo de volumes contiver todas as unidades FIPS (Federal Information Processing Standards), as unidades não FIPS não serão listadas.
* Se um pool ou grupo de volumes contiver todas as unidades compatíveis com Data Assurance (DA) e houver pelo menos um volume habilitado PARA DA no pool ou grupo de volumes, uma unidade que não seja capaz de DA não é elegível, portanto, ela não pode ser adicionada a esse pool ou grupo de volumes. No entanto, se não houver um volume habilitado PARA DA no pool ou grupo de volumes, uma unidade que não seja capaz de DA pode ser adicionada a esse pool ou grupo de volumes. Se você decidir misturar essas unidades, lembre-se de que não é possível criar nenhum volume habilitado PARA DA.



NOTE: A capacidade pode ser aumentada em seu storage array adicionando novas unidades ou excluindo pools ou grupos de volumes.
