---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-remove-storage-arrays-from-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Remova um ou mais arrays de armazenamento gerenciados de um grupo se você não quiser mais gerenciá-lo de um grupo de armazenamento específico. 
---
= Remova os storage arrays de um grupo no plug-in de armazenamento do SANtricity para vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode remover um ou mais arrays de armazenamento gerenciados de um grupo se não quiser mais gerenciá-los de um grupo de armazenamento específico.

.Sobre esta tarefa
A remoção de matrizes de armazenamento de um grupo não afeta a matriz de armazenamento ou os seus dados de forma alguma. Se o storage array for gerenciado pelo System Manager, você ainda poderá gerenciá-lo usando o navegador. Se um storage array for removido acidentalmente de um grupo, ele poderá ser adicionado novamente.

.Passos
. Na página Gerenciar, selecione menu:Gerenciar grupos[Remover matrizes de armazenamento do grupo].
. Na lista suspensa, selecione o grupo que contém os storages de armazenamento que deseja remover e clique na caixa de seleção ao lado de cada storage array que você deseja remover do grupo.
. Clique em *Remover*.

