---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-when-would-i-want-to-use-the-assign-host-later-selection.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Se você quiser acelerar o processo de criação de volumes, você pode pular a etapa de atribuição do host para que os volumes recém-criados sejam inicializados offline. 
---
= Quando eu gostaria de usar a seleção atribuir host mais tarde?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se você quiser acelerar o processo de criação de volumes, você pode pular a etapa de atribuição do host para que os volumes recém-criados sejam inicializados offline.

Os volumes recém-criados devem ser inicializados. O sistema pode iniciá-los usando um de dois modos – um processo de inicialização em segundo plano formato disponível imediato (IAF) ou um processo offline.

Quando você mapeia um volume para um host, ele força qualquer volume inicializando nesse grupo a transição para a inicialização em segundo plano. Esse processo de inicialização em segundo plano permite e/S de host concorrente, que às vezes pode ser demorado.

Quando nenhum dos volumes de um grupo de volumes é mapeado, a inicialização offline é realizada. O processo off-line é muito mais rápido do que o processo em segundo plano.
