---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-storage-configuration-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Importe a configuração de armazenamento de um storage array para outros storage arrays. 
---
= Importar definições de configuração de armazenamento
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode importar a configuração de armazenamento de um storage array para outros storage arrays. Esta operação em lote economiza tempo quando você precisa configurar vários arrays na rede.

.Antes de começar
Certifique-se de que:

* O armazenamento é configurado no System Manager para a matriz de armazenamento que você deseja usar como origem.
* A configuração existente para os storages de armazenamento de destino é feita com backup no System Manager (menu:Configurações[sistema > Salvar configuração da matriz de armazenamento]).
* Você analisou os requisitos para replicação de configurações de storage no link:vc-olh-import-settings-overview.html["Descrição geral das definições de importação"].
* Os arrays de origem e destino devem atender a estes requisitos:
+
** As gavetas em que os controladores residem devem ser idênticas.
** As IDs de gaveta devem ser idênticas.
** Os compartimentos de expansão devem ser preenchidos nos mesmos slots com os mesmos tipos de unidades.
** O tipo de compartimento RBOD deve ser idêntico.
** As HICs, incluindo os recursos de Garantia de dados do host, devem ser idênticas.
** Os arrays de destino devem estar no status ideal.
** A capacidade de volume no array de destino é maior do que a capacidade do array de origem.


* Você entende as seguintes restrições:
+
** A importação de uma configuração duplex para simplex não é suportada; no entanto, a importação de simplex para duplex é permitida.
** Volumes de pool de discos de 64 TB ou maiores no array de origem impedirão o processo de importação nos destinos.




.Sobre esta tarefa
As configurações importadas incluem volumes configurados (somente volumes espessos e não-repositórios), grupos de volumes, pools e atribuições de unidades hot spare.

.Passos
. Na página Gerenciar, clique em menu:ações[Importar configurações].
+
O assistente Importar configurações é aberto.

. Na caixa de diálogo Selecionar configurações, selecione *Configuração de armazenamento* e clique em *Avançar*.
+
Abre-se uma caixa de diálogo para selecionar a matriz de origem.

. Na caixa de diálogo Selecionar fonte, selecione a matriz com as configurações que deseja importar e clique em *Avançar*.
. Na caixa de diálogo Selecionar destinos, selecione um ou mais arrays para receber as novas configurações.
+

NOTE: Matrizes de armazenamento com firmware abaixo de 8,50 não estão disponíveis para seleção. Além disso, uma matriz não aparece nesta caixa de diálogo se o plugin não puder se comunicar com essa matriz (por exemplo, se estiver offline ou se tiver problemas de certificado, senha ou rede).

. Clique em *Finish*.
+
A página operações exibe os resultados da operação de importação. Se a operação falhar, você pode clicar em sua linha para ver mais informações.



.Resultado
Os storage arrays de destino agora são configurados com a mesma configuração de armazenamento que o array de origem.
