---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-pools-and-volume-group-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: 'Para provisionar o armazenamento, você cria um pool ou um grupo de volumes que conterá as unidades de disco rígido (HDD) ou de disco de estado sólido (SSD) que você deseja usar em seu storage array.' 
---
= Visão geral de pools e grupos de volumes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para provisionar o armazenamento no plug-in de armazenamento para vCenter, você cria um pool ou um grupo de volumes que conterá as unidades de disco rígido (HDD) ou de disco de estado sólido (SSD) que você deseja usar em seu storage array.



== Provisionamento

O hardware físico é provisionado em componentes lógicos para que os dados possam ser organizados e facilmente recuperados. Há dois tipos de agrupamentos suportados:

* Piscinas
* Grupos de volume


Os pools e grupos de volumes são as unidades de armazenamento de nível superior em um storage array: Dividem a capacidade das unidades em divisões gerenciáveis. Dentro dessas divisões lógicas estão os volumes individuais ou LUNs onde os dados são armazenados.

Quando um sistema de storage é implantado, a primeira etapa é apresentar a capacidade de unidade disponível para os vários hosts:

* Criação de pools ou grupos de volumes com capacidade suficiente
* Adicionar o número de unidades necessárias para atender aos requisitos de desempenho ao pool ou ao grupo de volumes
* Selecionar o nível desejado de proteção RAID (se estiver usando grupos de volume) para atender a requisitos empresariais específicos


Você pode ter pools ou grupos de volume no mesmo sistema de armazenamento, mas uma unidade não pode fazer parte de mais de um pool ou grupo de volumes. Os volumes que são apresentados aos hosts para e/S são então criados, usando o espaço no pool ou grupo de volumes.



== Piscinas

Os pools foram projetados para agregar unidades de disco rígido físicas em um grande espaço de armazenamento e oferecer proteção RAID aprimorada para ele. Um pool cria muitos conjuntos de RAID virtuais a partir do número total de unidades atribuídas ao pool e distribui os dados uniformemente entre todas as unidades participantes. Se uma unidade for perdida ou adicionada, o sistema reequilibra dinamicamente os dados em todas as unidades ativas.

Os pools funcionam como outro nível RAID, virtualizando a arquitetura RAID subjacente para otimizar o desempenho e a flexibilidade ao executar tarefas como reconstrução, expansão da unidade e manipulação da perda da unidade. O sistema define automaticamente o nível RAID como 6 em uma configuração 8 mais 2 (oito discos de dados mais dois discos de paridade).



=== Correspondência de condução

Você pode escolher entre HDD ou SSDs para uso em pools. No entanto, assim como nos grupos de volumes, todas as unidades do pool precisam usar a mesma tecnologia. Os controladores selecionam automaticamente quais unidades incluir, portanto, você deve ter certeza de que tem um número suficiente de unidades para a tecnologia escolhida.



=== Gerenciamento de unidades com falha

Os pools têm uma capacidade mínima de 11 unidades. No entanto, uma unidade de capacidade é reservada para capacidade extra em caso de falha da unidade. Essa capacidade extra é chamada de "capacidade de preservação".

Quando os pools são criados, uma certa quantidade de capacidade é preservada para uso de emergência. Essa capacidade é expressa em termos de várias unidades, mas a implementação real é distribuída por todo o pool de unidades. A quantidade padrão de capacidade preservada é baseada no número de unidades no pool.

Depois que o pool é criado, você pode alterar o valor da capacidade de preservação para mais ou menos capacidade, ou até mesmo configurá-lo para nenhuma capacidade de preservação (valor de 0 unidades). A quantidade máxima de capacidade que pode ser preservada (expressa como um número de unidades) é de 10 TB, mas a capacidade disponível pode ser menor, com base no número total de unidades no pool.



== Grupos de volume

Os grupos de volume definem como a capacidade é alocada no sistema de storage para volumes. As unidades de disco são organizadas em grupos RAID e os volumes residem nas unidades de um grupo RAID. Portanto, as configurações do grupo de volume identificam quais unidades fazem parte do grupo e qual nível RAID é usado.

Quando você cria um grupo de volumes, os controladores selecionam automaticamente as unidades a serem incluídas no grupo. Você deve escolher manualmente o nível RAID para o grupo. A capacidade do grupo de volumes é o total do número de unidades selecionadas, multiplicado pela sua capacidade.



=== Correspondência de condução

Você deve corresponder as unidades no grupo de volumes para tamanho e desempenho. Se houver unidades menores e maiores no grupo de volumes, todas as unidades serão reconhecidas como o menor tamanho de capacidade. Se houver unidades mais lentas e mais rápidas no grupo de volumes, todas as unidades são reconhecidas na velocidade mais lenta. Esses fatores afetam o desempenho e a capacidade geral do sistema de storage.

Não é possível misturar diferentes tecnologias de unidade (unidades HDD e SSD). RAID 3, 5 e 6 estão limitados a um máximo de 30 unidades. RAID 1 e RAID 10 usam espelhamento, portanto, esses grupos de volume devem ter um número par de discos.



=== Gerenciamento de unidades com falha

Os grupos de volume usam unidades hot spare como modo de espera no caso de uma unidade falhar nos volumes RAID 1/10, RAID 3, RAID 5 ou RAID 6 contidos em um grupo de volumes. Uma unidade hot spare não contém dados e adiciona outro nível de redundância à sua matriz de armazenamento.

Se uma unidade falhar no storage de armazenamento, a unidade hot spare será automaticamente substituída pela unidade com falha sem exigir uma troca física. Se a unidade hot spare estiver disponível quando uma unidade falhar, a controladora usará dados de redundância para reconstruir os dados da unidade com falha para a unidade hot spare.



== Decida se deseja usar pools ou grupos de volume



=== Escolha uma piscina

* Se você precisar de reconstruções de unidades mais rápidas e administração simplificada de storage e/ou tiver um workload altamente aleatório.
* Se você quiser distribuir os dados para cada volume aleatoriamente em um conjunto de unidades que compõem o pool.você não pode definir ou alterar o nível RAID de pools ou os volumes nos pools. Os pools usam RAID nível 6.




=== Escolha um grupo de volumes

* Se você precisar de largura de banda máxima do sistema, a capacidade de ajustar as configurações de storage e um workload altamente sequencial.
* Se você quiser distribuir os dados entre as unidades com base em um nível RAID. Você pode especificar o nível RAID ao criar o grupo de volumes.
* Se você quiser gravar os dados para cada volume sequencialmente no conjunto de unidades que compõem o grupo de volumes.



NOTE: Como os pools podem coexistir com grupos de volume, um storage array pode conter pools e grupos de volume.



== Criação automática versus manual de pool

Dependendo da sua configuração de armazenamento, você pode permitir que o sistema crie pools automaticamente ou você mesmo pode criá-los manualmente. Um pool é um conjunto de unidades agrupadas logicamente.

Antes de criar e gerenciar pools, consulte as seções a seguir para saber como os pools são criados automaticamente e quando você pode precisar criá-los manualmente.



=== Criação automática

Quando o sistema deteta capacidade não atribuída no storage array, ele inicia a criação automática de pool quando o sistema deteta capacidade não atribuída em um storage array. Ele solicita automaticamente que você crie um ou mais pools ou adicione a capacidade não atribuída a um pool existente ou a ambos.

A criação automática de pool ocorre quando uma destas condições é verdadeira:

* Os pools não existem no storage array e há unidades similares suficientes para criar um novo pool.
* Novas unidades são adicionadas a um storage que tenha pelo menos um pool.cada unidade em um pool deve ser do mesmo tipo de unidade (HDD ou SSD) e ter capacidade semelhante. O sistema solicitará que você conclua as seguintes tarefas:
* Crie um único pool se houver um número suficiente de unidades desses tipos.
* Crie vários pools se a capacidade não atribuída consistir em diferentes tipos de unidade.
* Adicione as unidades ao pool existente se um pool já estiver definido no storage de armazenamento e adicione novas unidades do mesmo tipo de unidade ao pool.
* Adicione as unidades do mesmo tipo de unidade ao pool existente e use os outros tipos de unidade para criar pools diferentes se as novas unidades forem de tipos de unidade diferentes.




=== Criação manual

Você pode querer criar um pool manualmente quando a criação automática não puder determinar a melhor configuração. Esta situação pode ocorrer por uma das seguintes razões:

* As novas unidades podem ser potencialmente adicionadas a mais de um pool.
* Um ou mais dos novos candidatos à piscina podem usar proteção contra perda de prateleira ou proteção contra perda de gaveta.
* Um ou mais candidatos ao pool atual não podem manter o status de proteção contra perda de gaveta ou proteção contra perda de gaveta. Você também pode querer criar um pool manualmente se tiver vários aplicativos em seu storage array e não quiser que eles concorram pelos mesmos recursos de unidade. Nesse caso, você pode considerar a criação manual de um pool menor para um ou mais aplicativos. Você pode atribuir apenas um ou dois volumes em vez de atribuir a carga de trabalho a um pool grande que tenha muitos volumes para distribuir os dados. A criação manual de um pool separado dedicado ao workload de uma aplicação específica pode permitir que as operações de storage array tenham performance mais rápida, com menos contenção.

