---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-how-do-i-maintain-shelf-and-drawer-loss-protection.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Mantenha a proteção contra perda de gaveta e gaveta para um pool ou grupo de volume 
---
= Como faço para manter a proteção contra perda de prateleira e gaveta?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Para manter a proteção contra perda de gaveta e gaveta para um pool ou grupo de volumes, use os critérios especificados na tabela a seguir.

|===
| Nível | Critérios para proteção contra perda de prateleira/gaveta | Número mínimo de prateleiras / gavetas necessário 


| Piscina | Para gavetas, o pool não deve conter mais de duas unidades em uma única gaveta. Para gavetas, o pool deve incluir um número igual de unidades de cada gaveta. | 6 para prateleiras 5 para gavetas 


| RAID 6 | O grupo de volumes não contém mais do que duas unidades em um único compartimento ou gaveta. | 3 


| RAID 3 ou RAID 5 | Cada unidade no grupo de volume está localizada em uma gaveta ou gaveta separada. | 3 


| RAID 1 | Cada unidade em um par espelhado deve estar localizada em uma gaveta ou gaveta separada. | 2 


| RAID 0 | Não é possível obter proteção contra perda de prateleira/gaveta. | Não aplicável 
|===

NOTE: A proteção contra perda de gaveta/gaveta não será mantida se uma unidade já tiver falhado no pool ou no grupo de volumes. Nessa situação, perder o acesso a um compartimento de unidades ou gaveta e, consequentemente, outra unidade no pool ou grupo de volume, causa perda de dados.
