---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-do-i-need-to-do-to-recognize-the-expanded-capacity.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Se você aumentar a capacidade de um volume, o host pode não reconhecer imediatamente o aumento da capacidade do volume. 
---
= O que eu preciso fazer para reconhecer a capacidade expandida?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se você aumentar a capacidade de um volume, o host pode não reconhecer imediatamente o aumento da capacidade do volume.

A maioria dos sistemas operacionais reconhece a capacidade de volume expandida e se expande automaticamente após a expansão de volume ser iniciada. No entanto, alguns podem não. Se o sistema operacional não reconhecer automaticamente a capacidade de volume expandido, talvez seja necessário realizar uma nova digitalização ou reinicialização do disco.

Depois de expandir a capacidade do volume, você deve aumentar manualmente o tamanho do sistema de arquivos para corresponder. A forma como você faz isso depende do sistema de arquivos que você está usando.

Consulte a documentação do sistema operacional do host para obter detalhes adicionais.
