---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-settings-are-imported.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: O recurso Importar configurações é uma operação em lote que carrega configurações de uma matriz de armazenamento para várias matrizes de armazenamento. As configurações importadas durante essa operação dependem de como o storage de armazenamento de origem é configurado no System Manager. 
---
= Que definições são importadas?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O recurso Importar configurações é uma operação em lote que carrega configurações de uma matriz de armazenamento para várias matrizes de armazenamento.

As configurações importadas durante essa operação dependem de como o storage de armazenamento de origem é configurado no System Manager. As seguintes configurações podem ser importadas para vários storages de armazenamento:

* *Alertas por e-mail* -- as configurações incluem um endereço de servidor de e-mail e os endereços de e-mail dos destinatários do alerta.
* *Alertas Syslog* -- as configurações incluem um endereço de servidor syslog e uma porta UDP.
* *Alertas SNMP* -- as configurações incluem um nome de comunidade e endereço IP para o servidor SNMP.
* *AutoSupport* -- as configurações incluem os recursos separados (AutoSupport Básico, OnDemand do AutoSupport e Diagnóstico remoto), a janela de manutenção, o método de entrega e o cronograma de envio.
* *Serviços de diretório* -- a configuração inclui o nome de domínio e URL de um servidor LDAP (Lightweight Directory Access Protocol), juntamente com os mapeamentos para os grupos de usuários do servidor LDAP para as funções predefinidas do storage array.
* *Configuração de armazenamento* -- as configurações incluem volumes (somente volumes espessos e somente não-repositórios), grupos de volumes, pools e atribuições de unidades hot spare.
* * Configurações do sistema* -- as configurações incluem configurações de varredura de Mídia para um volume, cache SSD para controladores e balanceamento de carga automático (não inclui relatórios de conetividade do host).

