---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-is-shelf-loss-protection-and-drawer-loss-protection.html 
keywords:  
summary:  
---
= O que é proteção contra perda de prateleira e proteção contra perda de gaveta?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
A proteção contra perda de gaveta e a proteção contra perda de gaveta são atributos de pools e grupos de volumes que permitem manter o acesso aos dados em caso de falha de gaveta ou gaveta única.



=== Proteção contra perda de prateleira

Um compartimento é o compartimento que contém as unidades ou as unidades e a controladora. A proteção contra perda de gaveta garante a acessibilidade aos dados nos volumes em um pool ou grupo de volumes se houver perda total de comunicação com um único compartimento de unidade. Um exemplo de perda total de comunicação pode ser perda de energia para o compartimento de unidades ou falha de ambos os módulos de e/S (IOMs).


NOTE: A proteção contra perda de gaveta não é garantida se uma unidade já tiver falhado no pool ou grupo de volumes. Nessa situação, a perda de acesso a um compartimento de unidades e, consequentemente, outra unidade no pool ou grupo de volumes causa a perda de dados.

Os critérios para a proteção contra perdas de prateleiras dependem do método de proteção, conforme descrito na tabela a seguir.

|===
| Nível | Critérios para proteção contra perdas de prateleira | Número mínimo de gavetas necessário 


| Piscina | O pool deve incluir unidades de pelo menos cinco gavetas, e deve haver um número igual de unidades em cada gaveta. A proteção contra perda de prateleira não é aplicável às prateleiras de alta capacidade; se o sistema contiver prateleiras de alta capacidade, consulte proteção contra perda de gaveta. | 5 


| RAID 6 | O grupo de volumes não contém mais do que duas unidades em uma única gaveta. | 3 


| RAID 3 ou RAID 5 | Cada unidade no grupo de volume está localizada em uma gaveta separada. | 3 


| RAID 1 | Cada unidade em um par RAID 1 deve estar localizada em uma gaveta separada. | 2 


| RAID 0 | Não é possível obter proteção contra perdas de prateleira. | Não aplicável 
|===


=== Proteção contra perda de gaveta

Uma gaveta é um dos compartimentos de uma prateleira que você puxa para fora para acessar as unidades. Apenas as prateleiras de alta capacidade têm gavetas. A proteção contra perda de gaveta garante a acessibilidade aos dados nos volumes em um pool ou grupo de volumes se ocorrer uma perda total de comunicação com uma única gaveta. Um exemplo de perda total de comunicação pode ser perda de energia para a gaveta ou falha de um componente interno dentro da gaveta.


CAUTION: A proteção contra perda de gaveta não é garantida se uma unidade já tiver falhado no pool ou grupo de volume. Nesta situação, perder o acesso a uma gaveta (e, consequentemente, outra unidade no pool ou grupo de volume) causa perda de dados.

Os critérios para a proteção contra perda de gaveta dependem do método de proteção, conforme descrito na seguinte tabela:

|===
| Nível | Critérios para proteção contra perda de gaveta | Número mínimo de gavetas necessário 


| Piscina | Os candidatos ao pool devem incluir unidades de todas as gavetas, e deve haver um número igual de unidades em cada gaveta. O pool deve incluir unidades de pelo menos cinco gavetas e deve haver um número igual de unidades em cada gaveta. Um compartimento de 60 unidades pode obter proteção contra perda de gaveta quando o pool contém 15, 20, 25, 30, 35, 40, 45, 50, 55 ou 60 unidades. Incrementos em múltiplos de 5 podem ser adicionados ao pool após a criação inicial. | 5 


| RAID 6 | O grupo de volumes não contém mais do que duas unidades em uma única gaveta. | 3 


| RAID 3 ou 5 | Cada unidade do grupo de volume está localizada em uma gaveta separada | 3 


| RAID 1 | Cada unidade em um par espelhado deve estar localizada em uma gaveta separada. | 2 


| RAID 0 | Não é possível obter proteção contra perda de gaveta. | Não aplicável 
|===