---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-raid-level-is-best-for-my-application.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Para maximizar o desempenho de um grupo de volumes, você deve selecionar o nível RAID apropriado. 
---
= Que nível RAID é melhor para a minha aplicação?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para maximizar o desempenho de um grupo de volumes, você deve selecionar o nível RAID apropriado.

Você pode determinar o nível RAID apropriado conhecendo as porcentagens de leitura e gravação dos aplicativos que estão acessando o grupo de volumes. Use a página desempenho para obter essas porcentagens.



== Níveis de RAID e desempenho do aplicativo

O RAID depende de uma série de configurações, chamadas níveis, para determinar como os dados de usuário e redundância são gravados e recuperados das unidades. Cada nível de RAID fornece recursos de desempenho diferentes. Os aplicativos com uma alta porcentagem de leitura terão bom desempenho usando volumes RAID 5 ou volumes RAID 6 devido ao excelente desempenho de leitura das configurações RAID 5 e RAID 6.

Os aplicativos com uma baixa porcentagem de leitura (com uso intenso de gravação) não funcionam tão bem nos volumes RAID 5 ou RAID 6. O desempenho degradado é o resultado da maneira como um controlador grava dados e dados de redundância nas unidades em um grupo de volumes RAID 5 ou em um grupo de volumes RAID 6.

Selecione um nível RAID com base nas seguintes informações.



=== RAID 0

*Descrição:*

* Modo de distribuição não redundante.
* O RAID 0 distribui os dados em todas as unidades do grupo de volumes.


*Caraterísticas de proteção de dados:*

* O RAID 0 não é recomendado para necessidades de alta disponibilidade. O RAID 0 é melhor para dados não críticos.
* Se uma única unidade falhar no grupo de volumes, todos os volumes associados falharão e todos os dados serão perdidos.


*Requisitos de número de unidade:*

* É necessário um mínimo de uma unidade para RAID nível 0.
* Os grupos de volume RAID 0 podem ter mais de 30 unidades.
* Você pode criar um grupo de volumes que inclua todas as unidades no storage array.




=== RAID 1 ou RAID 10

*Descrição:*

* Modo striping/mirror.


*Como funciona:*

* O RAID 1 usa o espelhamento de disco para gravar dados em dois discos duplicados simultaneamente.
* O RAID 10 usa o particionamento de unidades para distribuir dados em um conjunto de pares de unidades espelhadas.


*Caraterísticas de proteção de dados:*

* RAID 1 e RAID 10 oferecem alto desempenho e a melhor disponibilidade de dados.
* RAID 1 e RAID 10 usam espelhamento de unidade para fazer uma cópia exata de uma unidade para outra unidade.
* Se uma das unidades em um par de unidades falhar, o storage array pode alternar instantaneamente para a outra unidade sem perda de dados ou serviço.
* Uma única falha de unidade faz com que os volumes associados fiquem degradados. A unidade de espelho permite o acesso aos dados.
* Uma falha de par de unidade em um grupo de volumes faz com que todos os volumes associados falhem e a perda de dados possa ocorrer.


*Requisitos de número de unidade:*

* É necessário um mínimo de duas unidades para RAID 1: Uma unidade para os dados do usuário e uma unidade para os dados espelhados.
* Se você selecionar quatro ou mais unidades, o RAID 10 será configurado automaticamente no grupo de volumes: Duas unidades para dados de usuário e duas unidades para os dados espelhados.
* Você deve ter um número par de unidades no grupo de volumes. Se você não tiver um número par de unidades e tiver algumas unidades não atribuídas restantes, vá para *pools & grupos de volume* para adicionar unidades adicionais ao grupo de volumes e tente novamente a operação.
* Os grupos de volumes RAID 1 e RAID 10 podem ter mais de 30 unidades. É possível criar um grupo de volumes que inclua todas as unidades do storage array.




=== RAID 5

*Descrição:*

* Modo de e/S elevado.


*Como funciona:*

* Os dados do usuário e as informações redundantes (paridade) são distribuídos pelas unidades.
* A capacidade equivalente de uma unidade é usada para informações redundantes.


* Recursos de proteção de dados*

* Se uma única unidade falhar em um grupo de volumes RAID 5, todos os volumes associados ficarão degradados. As informações redundantes permitem que os dados ainda sejam acessados.
* Se duas ou mais unidades falharem em um grupo de volumes RAID 5, todos os volumes associados falharão e todos os dados serão perdidos.


*Requisitos de número de unidade:*

* Você precisa ter no mínimo três unidades no grupo de volumes.
* Normalmente, você está limitado a um máximo de 30 unidades no grupo de volumes.




=== RAID 6

*Descrição:*

* Modo de e/S elevado.


*Como funciona:*

* Os dados do usuário e as informações redundantes (paridade dupla) são distribuídos entre as unidades.
* A capacidade equivalente de duas unidades é usada para informações redundantes.


*Caraterísticas de proteção de dados:*

* Se uma ou duas unidades falharem em um grupo de volumes RAID 6, todos os volumes associados ficam degradados, mas as informações redundantes permitem que os dados ainda sejam acessados.
* Se três ou mais unidades falharem em um grupo de volumes RAID 6, todos os volumes associados falharão e todos os dados serão perdidos.


*Requisitos de número de unidade:*

* Você precisa ter no mínimo cinco unidades no grupo de volumes.
* Normalmente, você está limitado a um máximo de 30 unidades no grupo de volumes.



NOTE: Não é possível alterar o nível RAID de um pool. A interface do usuário configura automaticamente pools como RAID 6.



== Níveis de RAID e proteção de dados

RAID 1, RAID 5 e RAID 6 escrevem dados de redundância no suporte de dados da unidade para tolerância a falhas. Os dados de redundância podem ser uma cópia dos dados (espelhados) ou um código de correção de erros derivado dos dados. Você pode usar os dados de redundância para reconstruir rapidamente as informações em uma unidade de substituição se uma unidade falhar.

Você configura um único nível RAID em um único grupo de volumes. Todos os dados de redundância para esse grupo de volumes são armazenados dentro do grupo de volumes. A capacidade do grupo de volumes é a capacidade agregada das unidades membros menos a capacidade reservada para dados de redundância. A quantidade de capacidade necessária para redundância depende do nível RAID usado.
