---
permalink: maintenance-e5700/index.html 
sidebar: sidebar 
keywords: E5700 maintenance, repair E5700, replace E5700 components, E5724, EF570, E5760 
summary: Mantenha o hardware E5700 
---
= Mantenha o hardware E5700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Talvez seja necessário executar procedimentos de manutenção no hardware. Os procedimentos específicos para a manutenção dos componentes do sistema E5700 estão nesta seção.

Os procedimentos nesta seção pressupõem que o sistema E5700 já foi implantado no ambiente e-Series.



== Componentes do sistema

Para o sistema de armazenamento E5700, pode executar procedimentos de manutenção nos seguintes componentes.

[cols="25,65"]
|===


 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/batteries-intro-concept.html["Baterias"]
 a| 
Uma bateria é incluída com um recipiente do controlador e preserva os dados em cache se a energia CA falhar.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/controllers-overview-concept.html["Controladores"]
 a| 
Um controlador consiste em uma placa, firmware e software. Controla as unidades e implementa as funções do System Manager.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/canisters-overview-supertask-concept.html["Canisters"]
 a| 
Os coletores consistem em três tipos diferentes: Coletores de ventilador de energia (fontes de alimentação) que fornecem uma fonte de alimentação redundante e resfriamento adequado em um compartimento de controladora de 12 ou 24 unidades ou compartimento de unidades; coletores de energia usados para redundância de energia em um compartimento de controladora de 60 unidades ou compartimento de unidades; e coletores de ventilador usados para resfriamento do compartimento de controladora de 60 unidades ou compartimento de unidades.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/drives-overview-supertask-concept.html["Unidades"]
 a| 
Uma unidade é um dispositivo mecânico eletromagnético que fornece o meio de armazenamento físico para os dados.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/hics-overview-supertask-concept.html["Placas de interface de host (HICs)"]
 a| 
Uma placa de interface de host (HIC) pode ser instalada opcionalmente dentro de um recipiente de controlador. O controlador E5700 inclui portas de host integradas na própria placa controladora, bem como portas de host no HIC opcional. As portas de host que são incorporadas ao controlador são chamadas portas de host de placa base. As portas de host que são incorporadas ao HIC são chamadas portas HIC.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/hpp-overview-supertask-concept.html["Protocolo de porta de host"]
 a| 
Você pode converter o protocolo de um host para um protocolo diferente para que a compatibilidade e a comunicação possam ser estabelecidas.

|===