---
permalink: maintenance-ef600/batteries-overview-requirements-concept.html 
sidebar: sidebar 
keywords: replace EF300 battery, replace EF600 battery, EF300 battery fail, EF600 battery fail 
summary: Requisitos e considerações para a substituição da bateria EF300 ou EF600. 
---
= Requisitos para a substituição da bateria EF300 ou EF600
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de substituir uma bateria de EF300 V ou EF600 V, reveja os requisitos e considerações.

Uma bateria é incluída com um controlador e preserva os dados em cache se a energia CA falhar.



== Alertas do Recovery Guru

Se o Guru de recuperação no Gerenciador de sistema do SANtricity relatar um dos seguintes status, você deve substituir a bateria afetada:

* Falha da bateria
* Substituição da bateria necessária


A partir do Gestor do sistema SANtricity, reveja os detalhes no Guru de recuperação para confirmar que existe um problema com uma bateria e para garantir que não é necessário resolver primeiro outros itens.



== Descrição geral do procedimento

Para proteger seus dados, você deve substituir uma bateria com falha o mais rápido possível.

A seguir, uma visão geral das etapas para substituir uma bateria em controladores EF300 ou EF600:

. Coloque o controlador offline.
. Retire o recipiente do controlador.
. Substitua a bateria.
. Substitua o recipiente do controlador.
. Coloque o controlador online.




== Requisitos

Se pretende substituir uma bateria, tem de ter:

* Uma bateria de substituição.
* Uma pulseira antiestática, ou você tomou outras precauções antiestáticas.
* Etiquetas para identificar cada cabo que está ligado ao recipiente do controlador.
* Uma estação de gerenciamento com um navegador que pode acessar o Gerenciador de sistema do SANtricity para o controlador. (Para abrir a interface do System Manager, aponte o navegador para o nome de domínio ou endereço IP do controlador.)
+
Opcionalmente, você pode usar a interface de linha de comando (CLI) para executar alguns dos procedimentos. Se você não tiver acesso à CLI, você poderá fazer um dos seguintes procedimentos:

+
** *Para Gerenciador de sistema SANtricity (versão 11,60 e superior)* -- Baixe o pacote CLI (arquivo zip) do Gerenciador de sistema. Aceda ao menu:Definições[sistema > Complementos > Interface de linha de comando]. Em seguida, você pode emitir comandos CLI de um prompt do sistema operacional, como o prompt do dos C:.
** *For SANtricity Storage Manager/Enterprise Management Window (EMW)* -- siga as instruções no guia expresso para baixar e instalar o software. Você pode executar comandos CLI do EMW selecionando menu:Ferramentas[Executar Script].



