---
permalink: config-windows/install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Windows Unified Host Utilities, express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries, SMcli, SMdevices 
summary: Instale o Windows Unified Host Utilities para o método Windows Express. 
---
= Instalar e configurar os Utilitários do Windows Unified Host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
As ferramentas Utilitários unificados de host do Windows ajudam você a conetar computadores host a sistemas de armazenamento NetApp e definir os parâmetros necessários em computadores host. Você também pode definir tempos limite de disco adequados para melhor desempenho de leitura/gravação com o armazenamento NetApp.


NOTE: Para obter mais informações, consulte o _Guia de instalação de utilitários do host do Windows,_ encontrado em http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61343["Documentação do NetApp: Utilitários do host"^].

.Passos
. Use o http://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] para determinar a versão apropriada dos Utilitários do Unified Host a ser instalada.
+
As versões são listadas em uma coluna dentro de cada configuração suportada.

. Faça download dos Utilitários do Unified Host em http://mysupport.netapp.com["Suporte à NetApp"^].
+

NOTE: Este pacote de utilitários não pode ser instalado usando o instalador do SANtricity Storage Manager.

+

NOTE: Como alternativa, você pode usar o comando SMcli `-identifyDevices` para executar as mesmas funções da ferramenta Unified Host Utility. O SMcli está incluído no sistema operacional SANtricity e pode ser baixado através do Gerenciador de sistemas SANtricity. Para obter mais informações sobre como fazer o download do SMcli através do Gerenciador do sistema do SANtricity, consulte o https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["Faça download do tópico interface de linha de comando (CLI) na Ajuda on-line do Gerenciador de sistema do SANtricity"^].


