---
permalink: config-windows/verify-windows-config-support-task.html 
sidebar: sidebar 
keywords: express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Verifique se a configuração do Windows é suportada. 
---
= Verifique o suporte à configuração do Windows no e-Series
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para garantir uma operação confiável, crie um plano de implementação e, em seguida, use a ferramenta de Matriz de interoperabilidade (IMT) do NetApp para verificar se toda a configuração é suportada.

.Passos
. Vá para http://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade do NetApp"^] .
. Clique no bloco *Storage Solution Search*.
. Na área menu:Protocolos[Host SAN], clique no botão *Add* ao lado de *e-Series SAN Host*.
. Clique em *Exibir critérios de pesquisa de refino*.
+
É apresentada a secção refinar critérios de pesquisa. Nesta seção, você pode selecionar o protocolo que se aplica, bem como outros critérios para a configuração, como sistema operacional, NetApp os e driver de vários caminhos de host. Selecione os critérios que você sabe que deseja para sua configuração e veja quais elementos de configuração compatíveis se aplicam. Conforme necessário, faça as atualizações para o seu sistema operativo e protocolo que são prescritas na ferramenta. As informações detalhadas para a configuração escolhida estão acessíveis na página Exibir configurações suportadas clicando na seta da página direita.

. Conforme necessário, faça as atualizações para o seu sistema operativo e protocolo, conforme listado na tabela.
+
|===
| Atualizações do sistema operacional | Protocolo | Atualizações relacionadas ao protocolo 


 a| 
Talvez seja necessário instalar drivers prontos para uso para garantir a funcionalidade e a capacidade de suporte adequados.

Cada fornecedor HBA tem métodos específicos para atualizar o código de inicialização e o firmware. Consulte a seção de suporte do site do fornecedor para obter as instruções e o software necessários para atualizar o código de inicialização e o firmware do HBA.
 a| 
FC
 a| 
Driver, firmware e código de inicialização do adaptador de barramento do host (HBA)



 a| 
ISCSI
 a| 
Driver de placa de interface de rede (NIC), firmware e código de inicialização.



 a| 
SAS
 a| 
Driver, firmware e código de inicialização do adaptador de barramento do host (HBA)

|===

