---
permalink: upgrade-controllers/remount-volumes-lsi-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, remount volume, upgrade LSI, vendor ID 
summary: Remonte os volumes se a atualização da controladora resultar na alteração da ID do fornecedor da LSI para A NetApp. 
---
= Remonte os volumes depois de mudar o fornecedor da LSI para A NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se a atualização do controlador resultar na alteração da ID do fornecedor do LSI para O NetApp, siga o procedimento apropriado para o tipo de host:

* <<Remonte volumes em um host AIX>>
* <<Remonte volumes em um host VMware>>
* <<Remonte volumes em um host do Windows>>




== Remonte volumes em um host AIX

Depois de substituir os controladores, você pode observar que o host mostra os novos volumes no storage array, mas também mostra os volumes originais como com falha.

.Passo
Se os volumes falhados aparecerem, execute o `cfgmgr` comando.



== Remonte volumes em um host VMware

Depois de substituir os controladores, poderá observar as seguintes condições:

* O VMware mostra novos caminhos para os volumes no storage array, mas também mostra os caminhos originais como caminhos mortos.
* Os hosts ainda listam os volumes no storage array como tendo IDs de fornecedor LSI. Isso pode ocorrer quando os volumes foram reivindicados pela regra LSI no início e, portanto, continue a usar a mesma regra LSI quando os volumes voltam à linha.
* O Nome de exibição não reflete a alteração de LSI para NetApp. Isso pode ocorrer porque o nome de exibição se tornou teste livre após a descoberta inicial. Nesse caso, você pode alterar o Nome de exibição manualmente.


.Passos
. Execute uma nova verificação em cada host.
. Interromper todas as operações de e/S de host para este subsistema.
. Recuperar os volumes sob a regra NetApp.
+
.. Executar o `esxcli storage core device list` comando. Verifique a saída do comando para identificar volumes cujos nomes têm o formulário `aa.xxxx`.
.. Execute o comando `do esxcli storage core claiming reclaim -d naa.xxxxx` para alterar a ID do fornecedor LSI para NetApp.






== Remonte volumes em um host do Windows

Após a substituição das controladoras, você precisa remontar os volumes em um host do Windows para permitir que os hosts conectados realizem operações de e/S com os volumes localizados no storage array atualizado.

.Passos
. No *Gerenciador de dispositivos*, selecione *Mostrar dispositivos ocultos*.
. Para cada dispositivo de disco SCSI NetApp listado no *Gerenciador de dispositivos*, clique com o botão direito do Mouse na entrada e selecione *Desinstalar*.
+
Se o Windows exibir uma caixa de diálogo com uma mensagem indicando que você deve reiniciar o host, conclua a desinstalação de todos os volumes antes de procurar hardware e reinicializar.

. Clique com o botão direito do rato em *Gestor de dispositivos* e, em seguida, selecione *Procurar alterações de hardware*.
. Reinicie o host.

