---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: Se você estiver atualizando os controladores E2800 e E5700 e o recurso Segurança da unidade estiver ativado, será necessário desbloquear manualmente as unidades. 
---
= Desbloquear unidades e-Series
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O recurso de Segurança da Unidade para esses controladores bloqueará as unidades parcialmente, externamente ou internamente. Se o recurso Segurança da unidade estiver ativado, você deverá desbloquear manualmente essas unidades.

Siga o procedimento apropriado para:

* <<Gerenciamento de chaves internas>>
* <<Gerenciamento de chaves externas>>




== Gerenciamento de chaves internas

Siga estas etapas para o gerenciamento de chaves internas quando todas as unidades estiverem bloqueadas.

.Sobre esta tarefa
Os controladores recém-trocados serão bloqueados com um código de exibição de sete segmentos de *L5*. Esse bloqueio ocorre quando nenhuma unidade pode executar a sincronização de código automático (ACS). Após a importação da chave de segurança, o ACS retoma e atualiza os novos controladores.


NOTE: Se você não estiver usando a porta de gerenciamento 1, tente com outros endereços IP padrão: Ctrl A porta 1: 169.254.128.101 Ctrl A porta 2: 169.254.128.102 Ctrl B porta 1: 169.254.128.101 Ctrl B porta 2: 169.254.128.102

.Passos
. Faça uma conexão ethernet direta e privada entre a matriz de armazenamento e o laptop ou PC do cliente SANtricity. Para fazer isso:
+
.. Use um cabo ethernet RJ45 para conetar o laptop à porta de gerenciamento 1 no controlador A..
.. Para concluir a conexão, talvez seja necessário atribuir o laptop a um endereço IP na mesma sub-rede que o controlador A. durante o bloqueio do controlador, o controlador A usa por padrão um endereço de gerenciamento de 169.254.128.101. Assim, você pode atribuir o laptop a uma sub-rede como "169.254.128.201".


. Usando o endereço IP 169.254.128.101 com nome de usuário *admin* e a senha em branco, importe a chave interna usando o `import storageArray securityKey file` comando CLI, com a chave de segurança salva link:prepare-upgrade-controllers-task.html["Prepare-se para atualizar os controladores"]do . Para obter informações sobre como usar esse comando, consulte https://docs.netapp.com/us-en/e-series-cli/index.html["Referência de interface de linha de comando"].
+
*Exemplo:* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
Como alternativa, você pode importar a chave interna através da API REST através da seguinte chamada: `/storage-systems/{system-id}/security-key/import`



Os controladores continuarão com o processo de sincronização de código automático das unidades e reiniciarão. Após a reinicialização, os controladores estarão acessíveis através da configuração IP original.



== Gerenciamento de chaves externas

Siga estas etapas para gerenciamento de chaves externas quando todas as unidades estiverem bloqueadas.

.Sobre esta tarefa
Os controladores recém-trocados serão bloqueados com um código de exibição de sete segmentos de *L5*. Esse bloqueio ocorre quando nenhuma unidade pode executar a sincronização de código automático (ACS). Após a importação da chave de segurança, o ACS retoma e atualiza os novos controladores.

.Passos
. Faça uma conexão ethernet direta e privada entre a matriz de armazenamento e o laptop ou PC do cliente SANtricity. Para fazer isso:
+
.. Use um cabo ethernet RJ45 para conetar o laptop à porta de gerenciamento 1 no controlador A..
.. Para concluir a conexão, talvez seja necessário atribuir o laptop a um endereço IP na mesma sub-rede que o controlador A. durante o bloqueio do controlador, o controlador A usa por padrão um endereço de gerenciamento de 169.254.128.101. Assim, você pode atribuir o laptop a uma sub-rede como "169.254.128.201".


. Usando a chave de segurança salva link:prepare-upgrade-controllers-task.html["Prepare-se para atualizar os controladores"]do , importe a chave externa para o endereço IP 169.254.128.101 com o nome de usuário *admin* e a senha permanecendo em branco.
+
*Exemplo:* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
Como alternativa, você pode importar a chave externa através da API REST através da seguinte chamada: `/storage-systems/{system-id}/security-key/import`

+
Os controladores continuarão com o processo de sincronização de código automático das unidades e reiniciarão. Após a reinicialização, os controladores estarão acessíveis através da configuração IP original.

. (Opcional) se necessário, as unidades podem ser rekeyed executando o seguinte:
+
*Exemplo:* `SMcli <original_controller _ip> -u admin -p "<original_array_password>" -c "create storageArray securityKey" passPhrase=\"passPhraseString\" file=\"filename\";”`


