---
permalink: upgrade-santricity/upgrade-drive-firmware-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, SANtricity, drive firmware, upgrade SANtricity, upgrade OS, upgrade E-Series, upgrade firmware, upgrading, upgrade IOM firmware, upgrade NVSRAM, upgrade controller 
summary: Você atualiza o firmware das suas unidades para se certificar de que você tem todos os recursos mais recentes e correções de bugs. 
---
= Atualizar o firmware da unidade e-Series e EF-Series
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Siga este procedimento para atualizar o firmware das suas unidades, o que garante que tem todas as funcionalidades e correções mais recentes.



== Passo 1: Baixe os arquivos de firmware da unidade

Nesta etapa, você acessa o site de suporte da NetApp para baixar os arquivos de firmware da unidade para o cliente de gerenciamento.

.Passos
. No Gerenciador de sistema do SANtricity, selecione menu:suporte[Centro de atualização].
. Em Atualização do firmware da unidade, clique em *suporte NetApp* e faça login no site de suporte da NetApp.
. No site de suporte, clique na guia *Downloads* e selecione *Unidade de disco e Matriz de firmware*.
. Selecione *e-Series e firmware de disco EF-Series.*
. Siga as instruções apresentadas no ecrã para transferir os ficheiros.




== Passo 2: Inicie a atualização do firmware da unidade

Nesta etapa, você atualiza o firmware das unidades.

.Antes de começar
* Faça backup dos dados usando backup de disco para disco, cópia de volume (para um grupo de volumes não afetado pela atualização de firmware planejada) ou um espelhamento remoto.
* Certifique-se de que o storage array tenha um status ideal.
* Certifique-se de que todas as unidades têm um estado ideal.
* Certifique-se de que nenhuma alteração de configuração esteja sendo executada no storage array.
* Entenda que se as unidades forem capazes de apenas uma atualização off-line, a atividade de e/S para todos os volumes associados às unidades será interrompida.


.Passos
. No Centro de Atualização do System Manager (menu:suporte[Centro de Atualização]), clique em *Begin Upgrade* na seção "Drive firmware upgrade".
+
É apresentada uma caixa de diálogo que lista os ficheiros de firmware da unidade atualmente em utilização.

. Extraia (descompacte) os arquivos que você baixou do site de suporte.
. Clique em *Procurar* e selecione os novos arquivos de firmware da unidade que você baixou no site de suporte.
+
Os arquivos de firmware da unidade têm um nome de arquivo semelhante ao `D_HUC101212CSS600_30602291_MS01_2800_0002` com a extensão `.dlp` do .

+
Você pode selecionar até quatro arquivos de firmware da unidade, um de cada vez. Se mais de um arquivo de firmware de unidade for compatível com a mesma unidade, você receberá um erro de conflito de arquivo. Decida qual arquivo de firmware da unidade você deseja usar para a atualização e remova o outro.

. Clique em *seguinte*.
+
A caixa de diálogo Selecionar unidades é exibida, que lista as unidades que você pode atualizar com os arquivos selecionados.

+
Apenas as unidades compatíveis aparecem.

+
O firmware selecionado para a unidade aparece na área de informações *firmware proposto*. Se tiver de alterar o firmware, clique em *Back* (anterior) para regressar à caixa de diálogo anterior.

. Selecione o tipo de atualização que deseja executar:
+
** *Online (padrão)* -- mostra as unidades que podem suportar um download de firmware _enquanto o storage array está processando I/o_. Não é necessário interromper a e/S para os volumes associados usando essas unidades quando você selecionar esse método de atualização. Essas unidades são atualizadas uma de cada vez, enquanto o storage array está processando e/S para essas unidades.
** *Offline (paralelo)* -- mostra as unidades que podem suportar um download de firmware _somente enquanto toda a atividade de e/S está parada_ em qualquer volume que use as unidades. Você deve parar toda a atividade de e/S em todos os volumes que usam as unidades que você está atualizando ao selecionar esse método de atualização. As unidades que não têm redundância devem ser processadas como uma operação off-line. Esse requisito inclui qualquer unidade associada ao cache SSD, um grupo de volumes RAID 0 ou qualquer pool ou grupo de volumes degradado. A atualização off-line (paralela) é normalmente mais rápida do que o método on-line (padrão).


. Na primeira coluna da tabela, selecione a unidade ou unidades que deseja atualizar.
. Clique em *Start* (Iniciar) e confirme que deseja executar a operação.
+
Se você precisar parar a atualização, clique em *Parar*. Todas as transferências de firmware atualmente em curso são concluídas. Quaisquer downloads de firmware que não tenham sido iniciados são cancelados.

+

CAUTION: Parar a atualização do firmware da unidade pode resultar em perda de dados ou unidades indisponíveis.

. (Opcional) para ver uma lista do que foi atualizado, clique em *Save Log*.
+
O arquivo é salvo na pasta Downloads do navegador com o nome `drive_upgrade_log-timestamp.txt`.

. Se ocorrer algum dos seguintes erros durante o procedimento de atualização, tome a ação recomendada apropriada.
+
|===
| Se encontrar este erro de transferência de firmware... | Em seguida, faça o seguinte... 


 a| 
** Unidades atribuídas com falha

 a| 
Um motivo para a falha pode ser que a unidade não tenha a assinatura apropriada. Certifique-se de que a unidade afetada é uma unidade autorizada. Entre em Contato com o suporte técnico para obter mais informações.

Ao substituir uma unidade, certifique-se de que a unidade de substituição tem uma capacidade igual ou superior à unidade com falha que está a substituir.

Você pode substituir a unidade com falha enquanto a matriz de armazenamento está recebendo e/S



 a| 
Verifique a matriz de armazenamento
 a| 
** Certifique-se de que foi atribuído um endereço IP a cada controlador.
** Certifique-se de que todos os cabos ligados ao controlador não estão danificados.
** Certifique-se de que todos os cabos estão bem ligados.




 a| 
Unidades hot spare integradas
 a| 
Esta condição de erro tem de ser corrigida antes de poder atualizar o firmware. Inicie o System Manager e use o Recovery Guru para resolver o problema.



 a| 
Grupos de volumes incompletos
 a| 
Se um ou mais grupos de volumes ou pools de discos estiverem incompletos, você deverá corrigir essa condição de erro antes de atualizar o firmware. Inicie o System Manager e use o Recovery Guru para resolver o problema.



 a| 
Operações exclusivas (exceto Mídia em segundo plano/varredura de paridade) atualmente em execução em qualquer grupo de volume
 a| 
Se uma ou mais operações exclusivas estiverem em andamento, as operações devem ser concluídas antes que o firmware possa ser atualizado. Use o System Manager para monitorar o andamento das operações.



 a| 
Volumes em falta
 a| 
Você deve corrigir a condição de volume ausente antes que o firmware possa ser atualizado. Inicie o System Manager e use o Recovery Guru para resolver o problema.



 a| 
Qualquer controlador em um estado diferente do ideal
 a| 
Um dos controladores de storage array precisa de atenção. Esta condição deve ser corrigida antes que o firmware possa ser atualizado. Inicie o System Manager e use o Recovery Guru para resolver o problema.



 a| 
Informações de partição de armazenamento incompatíveis entre gráficos de objetos do controlador
 a| 
Ocorreu um erro ao validar os dados nos controladores. Contacte o suporte técnico para resolver este problema.



 a| 
Verificação SPM verificar falha na verificação do controlador do banco de dados
 a| 
Ocorreu um erro de banco de dados de mapeamento de partições de armazenamento em um controlador. Contacte o suporte técnico para resolver este problema.



 a| 
Validação do banco de dados de configuração (se suportado pela versão do controlador do storage array)
 a| 
Ocorreu um erro de banco de dados de configuração em um controlador. Contacte o suporte técnico para resolver este problema.



 a| 
Verificações relacionadas com MEL
 a| 
Contacte o suporte técnico para resolver este problema.



 a| 
Mais de 10 eventos informativos ou críticos de mel foram relatados nos últimos 7 dias
 a| 
Contacte o suporte técnico para resolver este problema.



 a| 
Mais de 2 Página 2C Eventos críticos de mel foram relatados nos últimos 7 dias
 a| 
Contacte o suporte técnico para resolver este problema.



 a| 
Mais de 2 eventos de mel críticos de canal de unidade degradada foram relatados nos últimos 7 dias
 a| 
Contacte o suporte técnico para resolver este problema.



 a| 
Mais de 4 entradas críticas de mel nos últimos 7 dias
 a| 
Contacte o suporte técnico para resolver este problema.

|===


.O que se segue?
A atualização do firmware da unidade está concluída. Pode retomar as operações normais.
